apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: appdeploy
  labels:
    app: flask
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: appdeploy
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50